SUPPORTED_FILTER = (
    "AI Files (*.ai);;"
    "DWG Files (*.dwg);;"
    "DXF Files (*.dxf);;"
    "PLT Files (*.plt);;"
    "PDF Files (*.pdf);;"
    "NC Files (*.nc);;"
    "SVG Files (*.svg);;"
    "Bitmap Files (*.bmp);;"
    "PNG Files (*.png);;"
    "JPEG Files (*.jpg *.jpeg);;"
    "GIF Files (*.gif);;"
    "TIFF Files (*.tif *.tiff);;"
    "PCX Files (*.pcx);;"
    "TGA Files (*.tga);;"
    "WBMP Files (*.wbmp);;"
    "ICO Files (*.ico);;"
    "G-Code Files (*.gcode *.ngc);;"
    "Curve Files (*.cur);;"
    "All Files (*)"
)
